-- AlterTable
ALTER TABLE `student` ADD COLUMN `role` ENUM('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT') NOT NULL DEFAULT 'STUDENT';

-- AlterTable
ALTER TABLE `teacher` ADD COLUMN `role` ENUM('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT') NOT NULL DEFAULT 'TEACHER';
